### ISSUE TITLE
suggestions for rims pack 

### ISSUE THREAD

**Issue by ziangc** [50k-Customs/Wheels-Pack#1]
good day. i write to suggest improvements for rim pack: 
1. MAN rear axle hub (http://www.man.com.au/wp-content/uploads/download-manager-files/HY_HYD_Hypoid_Rear_Axles.pdf cover page) ; the current MAN rear axle hub is for Iveco. 
2. Iveco front axle hub (http://www.truck1.eu/img/Spare_parts_Axle_IVECO_STRALIS-xxl-2070/2070_9751187276.jpg)

many thanks for the work!

**Comment by simon50keda** [comment]
1. As for man rear axle I think it's more or less okay, because the pictures I find shows more or less that kinda axle. So if you want me to make better one you will have to supply some better reference pictures.
2. I will add IVECO front axle to todo list.

**Comment by ziangc** [comment]
http://www.truck.man.eu/man/media/content_medien/images/global_engines_2/motorenfotos/10_achsen_bus/On-Road_Bus_MAN_Hypoid-Hinterachse_HY-1336.jpg

(side profile of axle hub)

https://plus.google.com/photos/102165405693592819652/albums/6146906718332778193/6146906721837443362?banner=pwa&pid=6146906721837443362&oid=102165405693592819652

(head-on profile of axle hub).

you are right that there is actually very little difference between the
actual MAN rear axle and the one in your mod. the devil's detail lie in the
markings on the axle hub where you replace "( . )" with "- MAN -".

hope the pictures are clear enough.

regards.

**Comment by simon50keda** [comment]
Yep this pictures are better and yes I will add that to todo as well.

**Comment by ziangc** [comment]
thank you so much!

the current MAN rear axle will be a good iveco rear axle btw :)

On Monday, 10 August 2015, Simon Lušenc notifications@github.com wrote:

> Yep this pictures are better and yes I will add that to todo as well.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/50k-Customs/Wheels-Pack/issues/1#issuecomment-129403937
> .

## 

Regards,
Zi'ang

**Comment by CobraBlue6** [comment]
EDIT:
Closed manufactured safety ring -> moved to issue#2

**Comment by simon50keda** [comment]
Both axles are now done, safe commit for this issue is: https://github.com/50k-Customs/Wheels-Pack/commit/05d5c27058473cd03bd9eaff06e9134ca998a6cd

**Comment by ziangc** [comment]
thank you so much! splendid work there!

On 15 September 2015 at 14:33, Simon Lušenc notifications@github.com
wrote:

> Both axles are now done, safe commit for this issue is: 05d5c27
> https://github.com/50k-Customs/Wheels-Pack/commit/05d5c27058473cd03bd9eaff06e9134ca998a6cd
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/50k-Customs/Wheels-Pack/issues/1#issuecomment-140294351
> .

## 

Regards,
Zi'ang
