### ISSUE TITLE
Hub Misplaced on 9' MB Right Front Steel Wheel

### ISSUE THREAD

**Issue by CobraBlue6** [50k-Customs/Wheels-Pack#3]
I discovered the hub is misplaced on 9' MB right front wheel, affects with safety ring and without.
PIcture showing problem https://flic.kr/p/yyq1wS
I thought I'd let you know before the final release :)

**Comment by simon50keda** [comment]
Nice finding yes. Indeed I haven't went trough all of the combinations because there is to many :D

Thanks for reporting.

**Comment by simon50keda** [comment]
Fixed with commit: https://github.com/50k-Customs/Wheels-Pack/commit/50370a9ffe9f6d532060a27370fa142a4a41773d
