### ISSUE TITLE
improvement to rear alcoa rims 

### ISSUE THREAD

**Issue by ziangc** [50k-Customs/Wheels-Pack#5]
hi simon! im using your wheels pack, and i have to say that the recent additions, including abasstreppas's contributions are really wonderful! 

that said, i would like to raise a slight issue and make a related request at the same time. 

as discussed in your wheels pack forum thread, many people are asking about whether there will be 9" (' actually means feet) front alcoa rims wheels similar to the rear alcoa rims. 

issue: the holes in the rear alcoa rims arent aligned (they should be between the bolts rather than directly behind them. refer: http://imagehost.vendio.com/a/7940566/aview/1307037534839_031.JPG as an example of how the holes would be aligned 

request: the discussion mentioned that a rear rim turned 180 deg would give a alcoa front 9" rim. there was a related development by roadhunter/harald-rs in a 1.4.8 release (http://www.gamemoding.com/euro-truck-simulator-2-mods/man-wheel-pack.html), but the 9" alcoa front has never been seen then. 

will greatly appreciate if you could work on the 9" alcoa front rims! 

cheers!

**Comment by simon50keda** [comment]
There will most probably be no 9'' alcoa front rims. This package came more or less to an end, because there is already so many variants that as abass said "store page when buying a wheel is getting floated". 

But I will fix alcoa rear rim problem with screws ;)

**Comment by ziangc** [comment]
thanks for the update, and glad to know that you are working on the rear
rim issue :)

Does SCS software have any plans to delink the wheel hubs from the wheels,
similar to what was done for the wheels and tires in a previous release?

such a delinking should help to reduce the variants of wheels present
because the hubs are tied to the vehicle chassis instead of the wheel.

On 21 September 2015 at 15:55, Simon Lušenc notifications@github.com
wrote:

> There will most probably be no 9'' alcoa front rims. This package came
> more or less to an end, because there is already so many variants that as
> abass said "store page when buying a wheel is getting floated".
> 
> But I will fix alcoa rear rim problem with screws ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/50k-Customs/Wheels-Pack/issues/5#issuecomment-141901300
> .

## 

Regards,
Zi'ang

**Comment by simon50keda** [comment]
Nope there won't be "delinking" of hubs in near future. ;)

**Comment by simon50keda** [comment]
Fixed in commit: https://github.com/50k-Customs/Wheels-Pack/commit/5b59d31204ff716d5998751f13090f76c778889b
