### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by inrepublica** [50k-Customs/Wheels-Pack#7]
Hello,
Have you a template for making new tyres?

Best regards

**Comment by warningpz** [comment]
Hello.
Sorry but i cant help you.
Best regards

2015-10-20 9:17 GMT-07:00 clark17 <notifications@github.com>:

**Comment by simon50keda** [comment]
Hi, templates for rims and tires are added in commit: https://github.com/50k-Customs/Wheels-Pack/commit/1eaec8a54205a8267204005a2ab8a45e4b31b9fc

You can find them in "templates" folder.

Closed.

**Comment by inrepublica** [comment]
Thanks a lot!
