### ISSUE TITLE
Covers With Paintable Safety Rings?

### ISSUE THREAD

**Issue by LoaderSaints** [50k-Customs/Wheels-Pack#8]
I was just wondering if you could make variants of the Cover rims which have the Safety Ring painted for both 9' and 11'? So that the rim would basically be the same as the Safety Ring one but with the cover in the middle (the cover itself shouldn't be painted, just the Safety Ring bit). A combination of these two types of rims:
http://i.imgur.com/0gCPr6u.jpg
http://i.imgur.com/JINoIAb.jpg

Here you can see an image of what I mean on a real life truck: https://www.flickr.com/photos/43774620@N06/19171757681/in/photolist-vd9gCe-r6UcKt-cEbkmC-wEpJ6W-nrpiCS-rdSvQW-wjbYh1-qF4ivi-q8E5Qe-v8yp9R-rgb5bR-agGW2e-sTxQbC-aeetjE-o6747n-oPzKK7-y9xx75-nXJRR2-uEbsPY-oC7WCv-vBiz6V-txDNMX-mzZ4ug-pbsygV-uEiMrz-xkV8GK-pbsyVF-qV7ACj-nKnirn-nGeCiZ-vbCWDw-wBrrP1-dvGgHE-rf4YJJ-9stacv-pbs985-psEbcZ-pbrNSd-pbrirP-pbs8ao-psUNc7-nGYQxe-eAzozq-wEpQRx-uEZFxq-nXVvJh-pqUuf1-psWvHz-tv4R6a-k9KjbD

**Comment by simon50keda** [comment]
There won't be any mixture variants of the wheels.

However if you want that effect is best for you to paint the texture itself. 
1. Inside "templates" search for cover.png, where you can see the template for it. 
2. Textures you are looking for are in "/vehicle/truck/upgrade/rim/50k_shared/" named "cover_<brand>.dds", now paint it and it should work.

**Comment by LoaderSaints** [comment]
Ah okay. Thank you for the instructions. I managed to get the rims painted just like I wanted. :)
Problem solved.
