### ISSUE TITLE
Safety Rings No Longer Recolorable/repaintable

### ISSUE THREAD

**Issue by nabil77** [50k-Customs/Wheels-Pack#9]
i was download and testing the patch 1.22 public_beta, i enjoyed the game untill i realize something, and yes, the safety rings are no longer recolorable/repaintable.
here is the screenshot : https://flic.kr/p/BtGunF

and how to fix this? i'm waiting for your answer
Thank you.
(sorry if my english was terrible,i'm still learning english)

**Comment by simon50keda** [comment]
Hi,
unfortunately I know about this issue, but the thing is that this behaviour was disabled in the ETS2 code on purpose and I can not do anything about it currently.

Hopefully this behaviour will be altered in next game updates.
